rust_library(
    name = "runtime",
    crate = "service_runtime",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//src/control-plane/core:core",
        "//src/control-plane/postgres:postgres",
        "//src/services/store-config:store-config",
        "//third-party:axum",
        "//third-party:iceberg",
        "//third-party:object_store",
        "//third-party:sqlx",
        "//third-party:thiserror",
        "//third-party:tokio",
        "//third-party:tracing-subscriber",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "config",
    crate = "config",
    srcs = ["tests/config.rs"],
    crate_root = "tests/config.rs",
    edition = "2024",
    deps = [":runtime"],
)

rust_test(
    name = "init-tracing",
    crate = "init_tracing",
    srcs = ["tests/init_tracing.rs"],
    crate_root = "tests/init_tracing.rs",
    edition = "2024",
    deps = [":runtime"],
)

rust_test(
    name = "object-store-config",
    crate = "object_store_config",
    srcs = ["tests/object_store_config.rs"],
    crate_root = "tests/object_store_config.rs",
    edition = "2024",
    deps = [":runtime"],
)
