//! Freshness gate for the committed sqlx offline query cache.
//!
//! The compile-time `query!` macros in the postgres adapter validate against the
//! committed cache under `.sqlx/query-*.json` (regenerated by
//! `tools/sqlx-prepare.sh`). Each cache file is just sqlx's own serialized
//! `describe` output for one query. This test boots the hermetic Postgres, applies
//! migrations, then for every committed query re-runs `Executor::describe` against
//! the live schema
//! and asserts the result still matches the committed JSON — same sqlx version,
//! same describe logic, so it's apples-to-apples. A dropped/renamed column, a type
//! change, or a nullability shift all make this fail, naming the offending query.
//!
//! Column type comparison is EXACT: we serialize the live `PgTypeInfo` with
//! `serde_json::to_value` (sqlx-core is built with the `offline` feature, which
//! derives `Serialize` for `PgTypeInfo`) and compare to the committed `type_info`
//! Value — the very same serialization that produced the cache. No string fallback.

use control_plane_postgres::fixture::PgFixture;
use serde_json::Value;
use sqlx::postgres::PgConnectOptions;
use sqlx::{
    AssertSqlSafe, Column, Connection, Either, Executor, PgConnection, SqlSafeStr, TypeInfo,
};

/// One committed cache entry, parsed to just the fields we verify.
struct CachedQuery {
    file: String,
    query: String,
    /// Per-column (name, raw `type_info` JSON value).
    columns: Vec<(String, Value)>,
    /// `describe.nullable`, as committed (one entry per column).
    nullable: Vec<Option<bool>>,
    /// Number of bind parameters (length of `parameters.Left`).
    param_count: usize,
}

fn parse_cache_file(path: &std::path::Path) -> CachedQuery {
    let file = path
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("<?>")
        .to_string();
    let raw = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {file}: {e}"));
    let v: Value = serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parse {file}: {e}"));

    let query = v["query"]
        .as_str()
        .unwrap_or_else(|| panic!("{file}: missing string `query`"))
        .to_string();

    let describe = &v["describe"];

    let columns = describe["columns"]
        .as_array()
        .unwrap_or_else(|| panic!("{file}: missing `describe.columns` array"))
        .iter()
        .map(|c| {
            let name = c["name"]
                .as_str()
                .unwrap_or_else(|| panic!("{file}: column missing `name`"))
                .to_string();
            (name, c["type_info"].clone())
        })
        .collect();

    let nullable = describe["nullable"]
        .as_array()
        .unwrap_or_else(|| panic!("{file}: missing `describe.nullable` array"))
        .iter()
        .map(|n| n.as_bool())
        .collect();

    // parameters is `{"Left": [..]}` (count known) or `"Right"`/etc. We only assert count.
    let param_count = describe["parameters"]["Left"]
        .as_array()
        .map(|a| a.len())
        .unwrap_or(0);

    CachedQuery {
        file,
        query,
        columns,
        nullable,
        param_count,
    }
}

#[tokio::test]
async fn sqlx_cache_matches_live_schema() {
    let dir = std::env::var("LOOM_SQLX_DIR")
        .expect("LOOM_SQLX_DIR must point at the committed .sqlx cache dir");

    // Collect committed query-*.json files (sorted for stable failure ordering).
    let mut files: Vec<std::path::PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("read LOOM_SQLX_DIR {dir}: {e}"))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| {
            p.file_name()
                .and_then(|s| s.to_str())
                .is_some_and(|s| s.starts_with("query-") && s.ends_with(".json"))
        })
        .collect();
    files.sort();
    assert!(
        !files.is_empty(),
        "no query-*.json files found in LOOM_SQLX_DIR={dir}; cache should be non-empty"
    );

    let cached: Vec<CachedQuery> = files.iter().map(|p| parse_cache_file(p)).collect();

    // Boot the hermetic cluster + a migrated db.
    let fx = PgFixture::start();
    let (_cp, db) = fx.fresh_db().await;

    // Raw connection for `.describe` against the live, migrated schema.
    let opts = PgConnectOptions::new()
        .socket(fx.socket_path())
        .username("postgres")
        .database(&db);
    let mut conn = PgConnection::connect_with(&opts)
        .await
        .expect("connect for describe");

    let mut failures: Vec<String> = Vec::new();

    for q in &cached {
        // 1. describe must succeed (dropped/renamed table or column => error => drift).
        // Query text comes from the committed (already-validated) cache, so it's safe.
        let sql = AssertSqlSafe(q.query.clone()).into_sql_str();
        let described = match conn.describe(sql).await {
            Ok(d) => d,
            Err(e) => {
                failures.push(format!(
                    "{}: describe failed (schema drift?): {e}\n  query: {}",
                    q.file, q.query
                ));
                continue;
            }
        };

        let cols = described.columns();

        // 2. column count.
        if cols.len() != q.columns.len() {
            failures.push(format!(
                "{}: column count {} != committed {}\n  query: {}",
                q.file,
                cols.len(),
                q.columns.len(),
                q.query
            ));
            continue;
        }

        // 4. parameter count.
        if let Some(params) = described.parameters() {
            // Postgres always reports `Left(Vec<_>)`.
            let live_params = match params {
                Either::Left(types) => types.len(),
                Either::Right(n) => n,
            };
            if live_params != q.param_count {
                failures.push(format!(
                    "{}: parameter count {live_params} != committed {}\n  query: {}",
                    q.file, q.param_count, q.query
                ));
            }
        } else if q.param_count != 0 {
            failures.push(format!(
                "{}: live query has no parameters but committed {}\n  query: {}",
                q.file, q.param_count, q.query
            ));
        }

        // Per-column: name (2), type (5, exact), nullable (3).
        for (i, col) in cols.iter().enumerate() {
            let (cached_name, cached_type) = &q.columns[i];

            // 2. column name.
            if col.name() != cached_name {
                failures.push(format!(
                    "{}: column {i} name {:?} != committed {:?}\n  query: {}",
                    q.file,
                    col.name(),
                    cached_name,
                    q.query
                ));
            }

            // 5. column type — EXACT via sqlx's own Serialize impl for PgTypeInfo.
            let live_type = serde_json::to_value(col.type_info())
                .unwrap_or_else(|e| panic!("{}: serialize type_info: {e}", q.file));
            if &live_type != cached_type {
                failures.push(format!(
                    "{}: column {i} ({}) type_info {} != committed {} (sqlx pg name: {})\n  query: {}",
                    q.file,
                    cached_name,
                    live_type,
                    cached_type,
                    col.type_info().name(),
                    q.query
                ));
            }

            // 3. nullable for this column.
            let live_nullable = described.nullable(i);
            let cached_nullable = q.nullable.get(i).copied().flatten();
            if live_nullable != cached_nullable {
                failures.push(format!(
                    "{}: column {i} ({}) nullable {:?} != committed {:?}\n  query: {}",
                    q.file, cached_name, live_nullable, cached_nullable, q.query
                ));
            }
        }
    }

    drop(conn.close().await);

    assert!(
        failures.is_empty(),
        "committed .sqlx cache is stale vs live schema; re-run tools/sqlx-prepare.sh.\n{} drift(s):\n{}",
        failures.len(),
        failures.join("\n")
    );
}
