//! Physical GC of dead Iceberg-mirror bytes: end-capped rows of a LIVE table, and
//! every DROPPED incarnation of a `(schema, name)`.
//!
//! Every Iceberg retirement is an *end-cap*, not a delete: a row's `end_snapshot`
//! is set so older time-travel reads still see it, while the bytes (and, for
//! `data_file` rows, the Parquet object) live on. `gc_table` reclaims the
//! mirror-driven dead bytes under an age-based retention horizon `H`, without ever
//! breaking an in-window time-travel read: end-capped `data_file` rows + their
//! Parquet and end-capped inline rows for the live table, and — for each dropped
//! incarnation — its aged-out `data_file` Parquet plus, once its drop snapshot
//! `D = table.end_snapshot` ages past `H`, its physical `inline_<tid>` table and all
//! its child mirror rows (`vector_index`, `column`, `table`) and its `inline_trigger`.
//!
//! ## Safety invariant
//! A row is reclaimable iff `end_snapshot IS NOT NULL AND end_snapshot <= H`,
//! where `H = max(snapshot_id) WHERE snapshot_time < now() - retention` (the
//! youngest snapshot fully aged out of the window). The MVCC read predicate is
//! `begin_snapshot <= at AND (end_snapshot IS NULL OR end_snapshot > at)`; an
//! end-capped row with `end_snapshot = E` is visible only for `at < E`. The
//! oldest `at` any in-window reader may supply is a snapshot `> H`, so if
//! `E <= H` the row is invisible to every guaranteed read. Live rows
//! (`end_snapshot IS NULL`) are never touched.
//!
//! ## Snapshot age
//! The age horizon uses the existing `iceberg_mirror.snapshot.snapshot_time`
//! column (`default now()`, inserted inside the committing transaction by
//! `next_snapshot`), so it is the snapshot's commit time — no extra column is
//! needed.
//!
//! ## Ordering: commit-then-delete
//! The mirror is the source of truth. The transaction deletes the rows first;
//! the Parquet objects are deleted *after* commit. A failure between the two
//! degrades a file to the already-deferred orphaned-Parquet class — never data
//! loss, never a dangling mirror→file reference.
//!
//! ## SQL strategy
//! Static SQL uses the compile-time `sqlx::query!`/`query_scalar!` macros, verified
//! against the committed `.sqlx` cache (regenerated by `tools/sqlx-prepare.sh`). Only
//! the dynamic `inline_<table_id>` identifier — a table name, not a bind parameter —
//! uses a runtime `sqlx::query(AssertSqlSafe(...))`. Every query is exercised against a
//! real schema by the fixture tests in `tests/iceberg_gc.rs`.

use std::time::Duration;

use control_plane_core::{Result, TableRef};
use sqlx::{AssertSqlSafe, PgPool};
use time::OffsetDateTime;

use crate::backend;
use crate::iceberg_flush::lock_key;
use crate::iceberg_inline::inline_table_name;
use crate::iceberg_mirror::{dropped_table_ids, live_table_id};
use crate::iceberg_sql_catalog::SqlCatalog;

/// Counts of what a `gc_table` run reclaimed, for observability and tests.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct GcSummary {
    pub data_file_rows: u64,
    pub inline_rows: u64,
    pub objects_deleted: u64,
}

/// Reclaim aged-out end-capped rows + their Parquet for one table.
///
/// Serializes per-table against flush/overwrite via the shared advisory lock
/// (`lock_key`). Returns an empty summary (a no-op, not an error) when the table
/// has no live mirror row or when no snapshot has aged out.
pub async fn gc_table(
    catalog: &SqlCatalog,
    pool: &PgPool,
    table: &TableRef,
    retention: Duration,
) -> Result<GcSummary> {
    // Transaction-scoped advisory lock on the table's stable key — the SAME key
    // flush/overwrite take, so GC never races a concurrent flush on this table.
    let mut lock_tx = pool.begin().await.map_err(backend)?;
    let key = lock_key(&table.schema, &table.name);
    sqlx::query!("select pg_advisory_xact_lock($1)", key)
        .execute(&mut *lock_tx)
        .await
        .map_err(backend)?;

    let result = gc_locked(catalog, pool, table, retention).await;

    // Rolling back the lock-holding tx releases the advisory lock.
    drop(lock_tx.rollback().await);
    result
}

async fn gc_locked(
    catalog: &SqlCatalog,
    pool: &PgPool,
    table: &TableRef,
    retention: Duration,
) -> Result<GcSummary> {
    // 1. Horizon H = youngest snapshot fully aged out of the window. Applies to
    //    every incarnation (live and, in the dropped loop, each dropped one).
    //    `now()` is taken in Rust; sub-second precision is irrelevant at GC scale.
    //    `max()` over zero matching rows yields NULL → None → a clean no-op.
    let cutoff = OffsetDateTime::now_utc() - time::Duration::seconds(retention.as_secs() as i64);
    let horizon = crate::iceberg_mirror::horizon_before(pool, cutoff).await?;
    let Some(h) = horizon else {
        return Ok(GcSummary::default());
    };

    // 2. Resolve the (maybe) live incarnation AND every dropped incarnation.
    let mut conn = pool.acquire().await.map_err(backend)?;
    let live = live_table_id(&mut conn, &table.schema, &table.name).await?;
    let dropped = dropped_table_ids(&mut conn, &table.schema, &table.name).await?;
    drop(conn);

    // 3. Collect the reclaimable Parquet paths (before deleting the rows that name
    //    them), across the live incarnation and every dropped one.
    let mut paths: Vec<String> = Vec::new();
    if let Some(tid) = live {
        paths.extend(reclaimable_paths(pool, tid, h).await?);
    }
    for inc in &dropped {
        paths.extend(reclaimable_paths(pool, inc.table_id, h).await?);
        if inc.drop_snapshot <= h {
            paths.extend(vector_index_paths(pool, inc.table_id).await?);
        }
    }

    // 4. One transaction: delete the reclaimable mirror rows.
    let mut tx = pool.begin().await.map_err(backend)?;
    let mut data_file_rows = 0u64;
    let mut inline_rows = 0u64;
    if let Some(tid) = live {
        data_file_rows += delete_data_files(&mut tx, tid, h).await?;
        inline_rows += delete_end_capped_inline_rows(&mut tx, tid, h).await?;
    }

    // Dropped incarnations: always reclaim aged-out data files; drop the physical
    // inline table + metadata rows only once the DROP snapshot itself ages past H
    // (D <= h), so no in-window time-travel read as-of before the drop can reach it.
    for inc in &dropped {
        data_file_rows += delete_data_files(&mut tx, inc.table_id, h).await?;
        if inc.drop_snapshot <= h {
            // Full reclaim: no in-window time-travel read can reach this incarnation.
            // Delete EVERY child of iceberg_mirror.table before the table row (FK order):
            //   data_file (above) → vector_index → column → table.
            // Then the no-FK inline_trigger orphan, and the physical inline table.
            drop_inline_table(&mut tx, inc.table_id).await?;
            delete_vector_index_rows(&mut tx, inc.table_id).await?;
            delete_column_rows(&mut tx, inc.table_id).await?;
            delete_table_row(&mut tx, inc.table_id).await?;
            delete_inline_trigger_row(&mut tx, inc.table_id).await?;
            tracing::info!(
                table_id = inc.table_id,
                "gc: fully reclaimed dropped incarnation (dropped inline table + child mirror rows)"
            );
        }
    }
    tx.commit().await.map_err(backend)?;

    // 5. Commit-then-delete: reclaim the objects (Parquet data files + Puffin
    //    vector-index sidecars). A failed delete is logged and left as an orphan
    //    (never re-raised into a hard error).
    let mut objects_deleted = 0u64;
    for path in &paths {
        match catalog.delete_file(path).await {
            Ok(()) => objects_deleted += 1,
            Err(e) => tracing::warn!(
                error = %e,
                path = %path,
                "gc: failed to delete object; leaving as orphan"
            ),
        }
    }

    Ok(GcSummary {
        data_file_rows,
        inline_rows,
        objects_deleted,
    })
}

/// Parquet paths of `tid`'s data files reclaimable at horizon `h`
/// (`end_snapshot IS NOT NULL AND end_snapshot <= h`).
async fn reclaimable_paths(pool: &PgPool, tid: i64, h: i64) -> Result<Vec<String>> {
    sqlx::query_scalar!(
        "select path from iceberg_mirror.data_file \
         where table_id = $1 and end_snapshot is not null and end_snapshot <= $2",
        tid,
        h,
    )
    .fetch_all(pool)
    .await
    .map_err(backend)
}

/// Delete `tid`'s reclaimable data files (stats child first, then the rows).
/// Returns the number of `data_file` rows deleted.
async fn delete_data_files(conn: &mut sqlx::PgConnection, tid: i64, h: i64) -> Result<u64> {
    sqlx::query!(
        "delete from iceberg_mirror.data_file_column_stat \
         where data_file_id in ( \
             select data_file_id from iceberg_mirror.data_file \
             where table_id = $1 and end_snapshot is not null and end_snapshot <= $2)",
        tid,
        h,
    )
    .execute(&mut *conn)
    .await
    .map_err(backend)?;
    let rows = sqlx::query!(
        "delete from iceberg_mirror.data_file \
         where table_id = $1 and end_snapshot is not null and end_snapshot <= $2",
        tid,
        h,
    )
    .execute(&mut *conn)
    .await
    .map_err(backend)?
    .rows_affected();
    Ok(rows)
}

/// Delete end-capped inline rows (`end_snapshot <= h`) from `inline_<tid>`, if the
/// physical table exists. Returns the number of rows deleted.
async fn delete_end_capped_inline_rows(
    conn: &mut sqlx::PgConnection,
    tid: i64,
    h: i64,
) -> Result<u64> {
    let inline = inline_table_name(tid);
    let exists: Option<String> = sqlx::query_scalar(AssertSqlSafe("select to_regclass($1)::text"))
        .bind(&inline)
        .fetch_one(&mut *conn)
        .await
        .map_err(backend)?;
    if exists.is_none() {
        return Ok(0);
    }
    let rows = sqlx::query(AssertSqlSafe(format!(
        "delete from {inline} where end_snapshot is not null and end_snapshot <= $1"
    )))
    .bind(h)
    .execute(&mut *conn)
    .await
    .map_err(backend)?
    .rows_affected();
    Ok(rows)
}

/// Puffin sidecar object paths of `tid`'s vector-index bindings. Collected before the
/// rows are deleted so the objects reclaim post-commit (commit-then-delete, same policy
/// as Parquet data files).
async fn vector_index_paths(pool: &PgPool, tid: i64) -> Result<Vec<String>> {
    sqlx::query_scalar!(
        "select puffin_path from iceberg_mirror.vector_index where table_id = $1",
        tid,
    )
    .fetch_all(pool)
    .await
    .map_err(backend)
}

/// Delete every `iceberg_mirror.vector_index` row for `tid`. These rows FK-reference
/// `iceberg_mirror.table(table_id)` with no `ON DELETE`, so they MUST be deleted before
/// `delete_table_row` — otherwise the table-row delete FK-violates and aborts the whole
/// GC transaction.
async fn delete_vector_index_rows(conn: &mut sqlx::PgConnection, tid: i64) -> Result<()> {
    sqlx::query!(
        "delete from iceberg_mirror.vector_index where table_id = $1",
        tid,
    )
    .execute(&mut *conn)
    .await
    .map_err(backend)?;
    Ok(())
}

/// Delete the `iceberg_mirror.inline_trigger` row for `tid` (keyed by the stable
/// table_id, no FK). Prevents a permanent orphan row once a dropped incarnation is fully
/// reclaimed. Order-independent.
async fn delete_inline_trigger_row(conn: &mut sqlx::PgConnection, tid: i64) -> Result<()> {
    sqlx::query!(
        "delete from iceberg_mirror.inline_trigger where table_id = $1",
        tid,
    )
    .execute(&mut *conn)
    .await
    .map_err(backend)?;
    Ok(())
}

/// Physically drop the per-incarnation inline table `inline_<tid>` (idempotent).
/// Only called once a dropped incarnation is fully reclaimed, so it can never gain a
/// live row again. Postgres DDL is transactional, so this rolls back with the tx.
async fn drop_inline_table(conn: &mut sqlx::PgConnection, tid: i64) -> Result<()> {
    let inline = inline_table_name(tid);
    sqlx::query(AssertSqlSafe(format!("drop table if exists {inline}")))
        .execute(&mut *conn)
        .await
        .map_err(backend)?;
    Ok(())
}

/// Delete every `iceberg_mirror.column` row for `tid` (only after its data files are
/// gone — the FK from `column` to `table` is satisfied because we delete `table` last).
async fn delete_column_rows(conn: &mut sqlx::PgConnection, tid: i64) -> Result<()> {
    sqlx::query!("delete from iceberg_mirror.column where table_id = $1", tid)
        .execute(&mut *conn)
        .await
        .map_err(backend)?;
    Ok(())
}

/// Delete the `iceberg_mirror.table` row for `tid`. Its `column`/`data_file` children
/// must already be gone (delete order: data_file → column → table).
async fn delete_table_row(conn: &mut sqlx::PgConnection, tid: i64) -> Result<()> {
    sqlx::query!("delete from iceberg_mirror.table where table_id = $1", tid)
        .execute(&mut *conn)
        .await
        .map_err(backend)?;
    Ok(())
}
