load("//src:loom_test.bzl", "rust_test")
rust_library(
    name = "datafusion-io",
    crate = "datafusion_io",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//src/control-plane/core:core",
        "//src/loom-config:loom-config",
        "//third-party:arrow",
        "//third-party:bytes",
        "//third-party:datafusion",
        "//third-party:futures",
        "//third-party:object_store",
        "//third-party:parquet",
        "//third-party:serde",
        "//third-party:thiserror",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "write",
    crate = "write",
    srcs = ["tests/write.rs"],
    crate_root = "tests/write.rs",
    edition = "2024",
    deps = [
        ":datafusion-io",
        "//src/control-plane/core:core",
        "//third-party:arrow",
        "//third-party:datafusion",
        "//third-party:object_store",
        "//third-party:parquet",
        "//third-party:tokio",
    ],
)

rust_test(
    name = "infer",
    crate = "infer",
    srcs = ["tests/infer.rs"],
    crate_root = "tests/infer.rs",
    edition = "2024",
    deps = [":datafusion-io", "//third-party:arrow"],
)

rust_test(
    name = "logical-arrow",
    crate = "logical_arrow",
    srcs = ["tests/logical_arrow.rs"],
    crate_root = "tests/logical_arrow.rs",
    edition = "2024",
    deps = [
        ":datafusion-io",
        "//src/control-plane/core:core",
        "//third-party:arrow",
    ],
)

rust_test(
    name = "scan",
    crate = "scan",
    srcs = ["tests/scan.rs"],
    crate_root = "tests/scan.rs",
    edition = "2024",
    deps = [
        ":datafusion-io",
        "//src/control-plane/core:core",
        "//third-party:arrow",
        "//third-party:datafusion",
        "//third-party:object_store",
        "//third-party:tokio",
    ],
)

rust_test(
    name = "write-tuning",
    crate = "write_tuning",
    srcs = ["tests/write_tuning.rs"],
    crate_root = "tests/write_tuning.rs",
    edition = "2024",
    deps = [
        ":datafusion-io",
        "//third-party:serde_json",
    ],
)

rust_test(
    name = "job-config",
    crate = "job_config",
    srcs = ["tests/job_config.rs"],
    crate_root = "tests/job_config.rs",
    edition = "2024",
    deps = [
        ":datafusion-io",
        "//src/loom-config:loom-config",
    ],
)

rust_test(
    name = "single-file-write",
    crate = "single_file_write",
    srcs = ["tests/single_file_write.rs"],
    crate_root = "tests/single_file_write.rs",
    edition = "2024",
    deps = [
        ":datafusion-io",
        "//src/control-plane/core:core",
        "//third-party:arrow",
        "//third-party:datafusion",
        "//third-party:object_store",
        "//third-party:tokio",
    ],
)
