def t_cyclomatic: 15;
def t_cognitive:  15;
def t_mi:         20;
def t_sloc:       100;
def esc: (. // "") | tostring | gsub("\\|"; "\\|") | gsub("\n"; " ");
def num: (. // 0) | (.*100|round)/100;
( [ .[] | (.name | ltrimstr($root)) as $file
    | [ .. | objects | select(.kind=="function")
        | { file:$file, function:(.name // "<anon>"), line:(.start_line // 0),
            cc:(.metrics.cyclomatic.sum // 0), cog:(.metrics.cognitive.sum // 0),
            mi:(.metrics.mi.mi_visual_studio // 100), sloc:(.metrics.loc.sloc // 0) } ]
    | .[] ] ) as $fns
| ( ($waivers[0] // []) | map(.file + " " + .function) | unique ) as $waived
| ( $fns | map(select(((.file + " " + .function) | IN($waived[])) | not))
         | map(select(.cc > t_cyclomatic or .cog > t_cognitive or .mi < t_mi or .sloc > t_sloc))
         | sort_by(.file, .line) ) as $hot
| "<!-- census:begin -->\n"
+ "_Generated by `/loom-complexity` — do not hand-edit below. Thresholds: cyclomatic > \(t_cyclomatic), cognitive > \(t_cognitive), MI(VS) < \(t_mi), SLOC > \(t_sloc)._\n\n"
+ "## Hotspots (\($hot|length))\n\n"
+ ( if ($hot|length)==0 then "_None over threshold._\n"
    else "| File | Function | Cyclomatic | Cognitive | MI | SLOC |\n|---|---|---|---|---|---|\n"
       + ( $hot | map("| `\(.file|esc)` | `\(.function|esc)` | \(.cc|num) | \(.cog|num) | \(.mi|num) | \(.sloc|num) |") | join("\n") ) + "\n" end )
+ "\n"
+ ( if (($waivers[0]//[])|length) > 0
    then "<details>\n<summary><b>Accepted (waived)</b> — \(($waivers[0])|length)</summary>\n\n| File | Function | Reason |\n|---|---|---|\n"
       + ( ($waivers[0]//[]) | sort_by(.file, .function) | map("| `\(.file|esc)` | `\(.function|esc)` | \(.reason|esc) |") | join("\n") ) + "\n</details>\n"
    else "" end )
+ "<!-- census:end -->"
