load("//src:loom_test.bzl", "rust_test")
load("//src/control-plane/postgres:defs.bzl", "loom_fixture_test")

rust_library(
    name = "worker",
    crate = "control_plane_worker",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//src/control-plane/core:core",
        "//third-party:futures-util",
        "//third-party:tokio",
        "//third-party:tokio-util",
        "//third-party:tracing",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "worker_test",
    crate = "worker_test",
    srcs = ["tests/worker.rs"],
    crate_root = "tests/worker.rs",
    edition = "2024",
    deps = [
        ":worker",
        "//src/control-plane/core:core",
        "//src/control-plane/memory:memory",
        "//third-party:serde_json",
        "//third-party:tokio",
        "//third-party:tokio-util",
        "//third-party:tracing",
        "//third-party:tracing-test",
    ],
)

loom_fixture_test(
    name = "postgres-integration",
    crate = "worker_postgres_integration",
    srcs = ["tests/postgres.rs"],
    crate_root = "tests/postgres.rs",
    deps = [
        ":worker",
        "//src/control-plane/core:core",
        "//src/control-plane/postgres:postgres",
        "//third-party:serde_json",
        "//third-party:tokio",
        "//third-party:tokio-util",
    ],
)
