def esc: (. // "") | tostring | gsub("\\|"; "\\|") | gsub("\n"; " ");
( .duplicates // []
  | sort_by(-.line_count, .file1.path, .file1.start_line, .file2.path, .file2.start_line) ) as $dups
| (($baseline[0].entries // $baseline[0].duplicates) // []) as $accepted
| "<!-- census:begin -->\n"
+ "_Generated by `/loom-duplication` — do not hand-edit below. Minimum block: 20 lines. Pairs recorded in the baseline are suppressed._\n\n"
+ "## Duplicate pairs (\($dups|length))\n\n"
+ ( if ($dups|length)==0 then "_None over threshold._\n"
    else "| Lines | Site A | Site B |\n|---|---|---|\n"
       + ( $dups | map("| \(.line_count) | `\(.file1.path|esc):\(.file1.start_line)-\(.file1.end_line)` | `\(.file2.path|esc):\(.file2.start_line)-\(.file2.end_line)` |") | join("\n") ) + "\n" end )
+ "\n"
+ ( if ($accepted|length) > 0
    then "<details>\n<summary><b>Accepted (baselined)</b> — \($accepted|length) pair(s)</summary>\n\nRecorded in `docs/code-health/duplication-baseline.json` and suppressed above.\n</details>\n"
    else "" end )
+ "<!-- census:end -->"
