def esc: (. // "") | tostring | gsub("\\|"; "\\|") | gsub("\n"; " ");
( .duplicates // []
  | sort_by(-.line_count, .file1.path, .file1.start_line, .file2.path, .file2.start_line) ) as $dups
| (($baseline[0].entries) // []) as $accepted
| "<!-- census:begin -->\n"
+ "_Generated by `/loom-duplication` — do not hand-edit below. Minimum block: 20 lines."
+ ( if ($accepted|length) > 0 then " Accepted (baselined) pairs are suppressed from the table and listed below." else "" end )
+ "_\n\n"
+ "## Duplicate pairs (\($dups|length))\n\n"
+ ( if ($dups|length)==0 then "_None over threshold._\n"
    else "| Lines | Site A | Site B |\n|---|---|---|\n"
       + ( $dups | map("| \(.line_count) | `\(.file1.path|esc):\(.file1.start_line)-\(.file1.end_line)` | `\(.file2.path|esc):\(.file2.start_line)-\(.file2.end_line)` |") | join("\n") ) + "\n" end )
+ "\n"
+ ( if ($accepted|length) > 0
    then "<details>\n<summary><b>Accepted (baselined)</b> — \($accepted|length) pair(s)</summary>\n\n"
       + "Recorded in `docs/code-health/duplication-baseline.json` and suppressed above (matched by content hash, so exact line ranges are not stored).\n\n"
       + "| Lines | File A | File B |\n|---|---|---|\n"
       + ( $accepted | sort_by(-.line_count, .file1, .file2)
           | map("| \(.line_count) | `\(.file1|esc)` | `\(.file2|esc)` |") | join("\n") )
       + "\n</details>\n"
    else "" end )
+ "<!-- census:end -->"
