rust_library(
    name = "testkit",
    crate = "control_plane_testkit",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//src/control-plane/core:core",
        "//third-party:serde_json",
        "//third-party:time",
        "//third-party:tokio",
    ],
    visibility = ["PUBLIC"],
)
