rust_library(
    name = "memory",
    crate = "control_plane_memory",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//src/control-plane/core:core",
        "//third-party:async-trait",
        "//third-party:serde_json",
        "//third-party:time",
        "//third-party:uuid",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "queue",
    crate = "queue",
    srcs = ["tests/queue.rs"],
    crate_root = "tests/queue.rs",
    edition = "2024",
    deps = [":memory", "//src/control-plane/testkit:testkit", "//third-party:tokio"],
)

rust_test(
    name = "contract",
    crate = "contract",
    srcs = ["tests/contract.rs"],
    crate_root = "tests/contract.rs",
    edition = "2024",
    deps = [
        ":memory",
        "//src/control-plane/testkit:testkit",
        "//third-party:tokio",
    ],
)
